In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import pickle
import json

import warnings
warnings.filterwarnings('ignore')

In [2]:
# sectorGDP data
dtypes = {'cfips': str}

census_df = pd.read_csv('census_starter.csv', dtype=dtypes)

# filling in the leadning zero where cfips is 4 digits
census_df['cfips'] = census_df['cfips'].apply(lambda x: x.zfill(5))

census_df.head()

,pct_bb_2017,pct_bb_2018,pct_bb_2019,pct_bb_2020,pct_bb_2021,cfips,pct_college_2017,pct_college_2018,pct_college_2019,pct_college_2020,...,pct_it_workers_2017,pct_it_workers_2018,pct_it_workers_2019,pct_it_workers_2020,pct_it_workers_2021,median_hh_inc_2017,median_hh_inc_2018,median_hh_inc_2019,median_hh_inc_2020,median_hh_inc_2021
0,76.6,78.9,80.6,82.7,85.5,01001,14.5,15.9,16.1,16.7,...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
1,74.5,78.1,81.8,85.1,87.9,01003,20.4,20.7,21.0,20.2,...,1.4,1.3,1.4,1.0,1.3,52562,55962.0,58320,61756.0,64346.0
2,57.2,60.4,60.5,64.6,64.6,01005,7.6,7.8,7.6,7.3,...,0.5,0.3,0.8,1.1,0.8,33368,34186.0,32525,34990.0,36422.0
3,62.0,66.1,69.2,76.1,74.6,01007,8.1,7.6,6.5,7.4,...,1.2,1.4,1.6,1.7,2.1,43404,45340.0,47542,51721.0,54277.0
4,65.8,68.5,73.0,79.6,81.0,01009,8.7,8.1,8.6,8.9,...,1.3,1.4,0.9,1.1,0.9,47412,48695.0,49358,48922.0,52830.0

In [3]:
census_df.columns

Index(['pct_bb_2017', 'pct_bb_2018', 'pct_bb_2019', 'pct_bb_2020',
       'pct_bb_2021', 'cfips', 'pct_college_2017', 'pct_college_2018',
       'pct_college_2019', 'pct_college_2020', 'pct_college_2021',
       'pct_foreign_born_2017', 'pct_foreign_born_2018',
       'pct_foreign_born_2019', 'pct_foreign_born_2020',
       'pct_foreign_born_2021', 'pct_it_workers_2017', 'pct_it_workers_2018',
       'pct_it_workers_2019', 'pct_it_workers_2020', 'pct_it_workers_2021',
       'median_hh_inc_2017', 'median_hh_inc_2018', 'median_hh_inc_2019',
       'median_hh_inc_2020', 'median_hh_inc_2021'],
      dtype='object')

In [4]:
census_df.isna().sum()

pct_bb_2017              0
pct_bb_2018              0
pct_bb_2019              0
pct_bb_2020              1
pct_bb_2021              1
cfips                    0
pct_college_2017         0
pct_college_2018         0
pct_college_2019         0
pct_college_2020         1
pct_college_2021         1
pct_foreign_born_2017    0
pct_foreign_born_2018    0
pct_foreign_born_2019    0
pct_foreign_born_2020    1
pct_foreign_born_2021    1
pct_it_workers_2017      0
pct_it_workers_2018      1
pct_it_workers_2019      0
pct_it_workers_2020      1
pct_it_workers_2021      1
median_hh_inc_2017       0
median_hh_inc_2018       1
median_hh_inc_2019       0
median_hh_inc_2020       2
median_hh_inc_2021       2
dtype: int64

In [5]:
# show row index where there is a NaN value
census_df[census_df.isna().any(axis=1)]

,pct_bb_2017,pct_bb_2018,pct_bb_2019,pct_bb_2020,pct_bb_2021,cfips,pct_college_2017,pct_college_2018,pct_college_2019,pct_college_2020,...,pct_it_workers_2017,pct_it_workers_2018,pct_it_workers_2019,pct_it_workers_2020,pct_it_workers_2021,median_hh_inc_2017,median_hh_inc_2018,median_hh_inc_2019,median_hh_inc_2020,median_hh_inc_2021
92,80.5,79.1,80.4,NaN,NaN,02261,23.1,19.0,16.5,NaN,...,3.3,3.9,5.3,NaN,NaN,86019,82306.0,79867,NaN,NaN
1816,49.1,52.1,57.6,60.7,63.5,35039,12.0,12.5,12.6,10.6,...,0.8,NaN,0.8,0.4,0.7,33422,NaN,39952,42264.0,46994.0
2644,66.3,66.6,61.2,63.2,70.1,48243,18.4,16.0,10.8,14.3,...,0.0,0.0,0.0,0.0,0.0,46534,53194.0,53088,NaN,38659.0
2673,64.5,72.7,73.3,96.8,97.0,48301,4.7,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,80938,81875.0,83750,44076.0,NaN

In [6]:
census_df[census_df.isna().any(axis=1)]['cfips'].to_list()

['02261', '35039', '48243', '48301']

In [7]:
census_df[census_df['cfips'].isin(['02261', '35039', '48243', '48301'])]

,pct_bb_2017,pct_bb_2018,pct_bb_2019,pct_bb_2020,pct_bb_2021,cfips,pct_college_2017,pct_college_2018,pct_college_2019,pct_college_2020,...,pct_it_workers_2017,pct_it_workers_2018,pct_it_workers_2019,pct_it_workers_2020,pct_it_workers_2021,median_hh_inc_2017,median_hh_inc_2018,median_hh_inc_2019,median_hh_inc_2020,median_hh_inc_2021
92,80.5,79.1,80.4,NaN,NaN,02261,23.1,19.0,16.5,NaN,...,3.3,3.9,5.3,NaN,NaN,86019,82306.0,79867,NaN,NaN
1816,49.1,52.1,57.6,60.7,63.5,35039,12.0,12.5,12.6,10.6,...,0.8,NaN,0.8,0.4,0.7,33422,NaN,39952,42264.0,46994.0
2644,66.3,66.6,61.2,63.2,70.1,48243,18.4,16.0,10.8,14.3,...,0.0,0.0,0.0,0.0,0.0,46534,53194.0,53088,NaN,38659.0
2673,64.5,72.7,73.3,96.8,97.0,48301,4.7,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,80938,81875.0,83750,44076.0,NaN

### not much missing data, I would just impute with the geometric trend

In [8]:
# impute the pct_bb_2020 with the pct_bb_2019 * (pct_bb_2019/pct_bb_2017)**(1/2), keep 1 decimal place
census_df['pct_bb_2020'] = census_df.apply(lambda x: round(x['pct_bb_2019'] * (x['pct_bb_2019']/x['pct_bb_2017'])**(1/2), 1) if np.isnan(x['pct_bb_2020']) else x['pct_bb_2020'], axis=1)

In [9]:
census_df[census_df['cfips'].isin(['02261', '35039', '48243', '48301'])]

,pct_bb_2017,pct_bb_2018,pct_bb_2019,pct_bb_2020,pct_bb_2021,cfips,pct_college_2017,pct_college_2018,pct_college_2019,pct_college_2020,...,pct_it_workers_2017,pct_it_workers_2018,pct_it_workers_2019,pct_it_workers_2020,pct_it_workers_2021,median_hh_inc_2017,median_hh_inc_2018,median_hh_inc_2019,median_hh_inc_2020,median_hh_inc_2021
92,80.5,79.1,80.4,80.4,NaN,02261,23.1,19.0,16.5,NaN,...,3.3,3.9,5.3,NaN,NaN,86019,82306.0,79867,NaN,NaN
1816,49.1,52.1,57.6,60.7,63.5,35039,12.0,12.5,12.6,10.6,...,0.8,NaN,0.8,0.4,0.7,33422,NaN,39952,42264.0,46994.0
2644,66.3,66.6,61.2,63.2,70.1,48243,18.4,16.0,10.8,14.3,...,0.0,0.0,0.0,0.0,0.0,46534,53194.0,53088,NaN,38659.0
2673,64.5,72.7,73.3,96.8,97.0,48301,4.7,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,80938,81875.0,83750,44076.0,NaN

In [10]:
# impute the pct_bb_2021 with the pct_bb_2020 * (pct_bb_2019/pct_bb_2017)**(1/2), keep 1 decimal place
census_df['pct_bb_2021'] = census_df.apply(lambda x: round(x['pct_bb_2020'] * (x['pct_bb_2019']/x['pct_bb_2017'])**(1/2), 1) if np.isnan(x['pct_bb_2021']) else x['pct_bb_2021'], axis=1)

In [11]:
census_df[census_df['cfips'].isin(['02261', '35039', '48243', '48301'])]

,pct_bb_2017,pct_bb_2018,pct_bb_2019,pct_bb_2020,pct_bb_2021,cfips,pct_college_2017,pct_college_2018,pct_college_2019,pct_college_2020,...,pct_it_workers_2017,pct_it_workers_2018,pct_it_workers_2019,pct_it_workers_2020,pct_it_workers_2021,median_hh_inc_2017,median_hh_inc_2018,median_hh_inc_2019,median_hh_inc_2020,median_hh_inc_2021
92,80.5,79.1,80.4,80.4,80.4,02261,23.1,19.0,16.5,NaN,...,3.3,3.9,5.3,NaN,NaN,86019,82306.0,79867,NaN,NaN
1816,49.1,52.1,57.6,60.7,63.5,35039,12.0,12.5,12.6,10.6,...,0.8,NaN,0.8,0.4,0.7,33422,NaN,39952,42264.0,46994.0
2644,66.3,66.6,61.2,63.2,70.1,48243,18.4,16.0,10.8,14.3,...,0.0,0.0,0.0,0.0,0.0,46534,53194.0,53088,NaN,38659.0
2673,64.5,72.7,73.3,96.8,97.0,48301,4.7,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,80938,81875.0,83750,44076.0,NaN

In [12]:
# impute the pct_college_2020 with the pct_college_2019 * (pct_college_2019/pct_college_2017)**(1/2), keep 1 decimal place
census_df['pct_college_2020'] = census_df.apply(lambda x: round(x['pct_college_2019'] * (x['pct_college_2019']/x['pct_college_2017'])**(1/2), 1) if np.isnan(x['pct_college_2020']) else x['pct_college_2020'], axis=1)

# impute the pct_college_2021 with the pct_college_2020 * (pct_college_2019/pct_college_2017)**(1/2), keep 1 decimal place
census_df['pct_college_2021'] = census_df.apply(lambda x: round(x['pct_college_2020'] * (x['pct_college_2019']/x['pct_college_2017'])**(1/2), 1) if np.isnan(x['pct_college_2021']) else x['pct_college_2021'], axis=1)

# impute the pct_foreign_born_2020 with the pct_foreign_born_2019 * (pct_foreign_born_2019/pct_foreign_born_2017)**(1/2), keep 1 decimal place
census_df['pct_foreign_born_2020'] = census_df.apply(lambda x: round(x['pct_foreign_born_2019'] * (x['pct_foreign_born_2019']/x['pct_foreign_born_2017'])**(1/2), 1) if np.isnan(x['pct_foreign_born_2020']) else x['pct_foreign_born_2020'], axis=1)

# impute the pct_foreign_born_2021 with the pct_foreign_born_2019 * (pct_foreign_born_2019/pct_foreign_born_2017), keep 1 decimal place
census_df['pct_foreign_born_2021'] = census_df.apply(lambda x: round(x['pct_foreign_born_2019'] * (x['pct_foreign_born_2019']/x['pct_foreign_born_2017']), 1) if np.isnan(x['pct_foreign_born_2021']) else x['pct_foreign_born_2021'], axis=1)

# impute the pct_it_workers_2018 with the pct_it_workers_2017 * (pct_it_workers_2019/pct_it_workers_2017)**(1/2), keep 1 decimal place
census_df['pct_it_workers_2018'] = census_df.apply(lambda x: round(x['pct_it_workers_2017'] * (x['pct_it_workers_2019']/x['pct_it_workers_2017'])**(1/2), 1) if np.isnan(x['pct_it_workers_2018']) else x['pct_it_workers_2018'], axis=1)

# impute the pct_it_workers_2020 with the pct_it_workers_2019 * (pct_it_workers_2019/pct_it_workers_2017)**(1/2), keep 1 decimal place
census_df['pct_it_workers_2020'] = census_df.apply(lambda x: round(x['pct_it_workers_2019'] * (x['pct_it_workers_2019']/x['pct_it_workers_2017'])**(1/2), 1) if np.isnan(x['pct_it_workers_2020']) else x['pct_it_workers_2020'], axis=1)

# impute the pct_it_workers_2021 with the pct_it_workers_2019 * (pct_it_workers_2019/pct_it_workers_2017), keep 1 decimal place
census_df['pct_it_workers_2021'] = census_df.apply(lambda x: round(x['pct_it_workers_2019'] * (x['pct_it_workers_2019']/x['pct_it_workers_2017']), 1) if np.isnan(x['pct_it_workers_2021']) else x['pct_it_workers_2021'], axis=1)

# impute the median_hh_inc_2018 with the median_hh_inc_2017 * (median_hh_inc_2019/median_hh_inc_2017)**(1/2), keep 1 decimal place
census_df['median_hh_inc_2018'] = census_df.apply(lambda x: round(x['median_hh_inc_2017'] * (x['median_hh_inc_2019']/x['median_hh_inc_2017'])**(1/2), 1) if np.isnan(x['median_hh_inc_2018']) else x['median_hh_inc_2018'], axis=1)

# impute the median_hh_inc_2020 with the median_hh_inc_2019 * (median_hh_inc_2019/median_hh_inc_2017)**(1/2), keep 1 decimal place
census_df['median_hh_inc_2020'] = census_df.apply(lambda x: round(x['median_hh_inc_2019'] * (x['median_hh_inc_2019']/x['median_hh_inc_2017'])**(1/2), 1) if np.isnan(x['median_hh_inc_2020']) else x['median_hh_inc_2020'], axis=1)

# impute the median_hh_inc_2021 with the median_hh_inc_2019 * (median_hh_inc_2019/median_hh_inc_2017), keep 1 decimal place
census_df['median_hh_inc_2021'] = census_df.apply(lambda x: round(x['median_hh_inc_2019'] * (x['median_hh_inc_2019']/x['median_hh_inc_2017']), 1) if np.isnan(x['median_hh_inc_2021']) else x['median_hh_inc_2021'], axis=1)

In [13]:
census_df[census_df['cfips'].isin(['02261', '35039', '48243', '48301'])]

,pct_bb_2017,pct_bb_2018,pct_bb_2019,pct_bb_2020,pct_bb_2021,cfips,pct_college_2017,pct_college_2018,pct_college_2019,pct_college_2020,...,pct_it_workers_2017,pct_it_workers_2018,pct_it_workers_2019,pct_it_workers_2020,pct_it_workers_2021,median_hh_inc_2017,median_hh_inc_2018,median_hh_inc_2019,median_hh_inc_2020,median_hh_inc_2021
92,80.5,79.1,80.4,80.4,80.4,02261,23.1,19.0,16.5,13.9,...,3.3,3.9,5.3,6.7,8.5,86019,82306.0,79867,76958.0,74155.0
1816,49.1,52.1,57.6,60.7,63.5,35039,12.0,12.5,12.6,10.6,...,0.8,0.8,0.8,0.4,0.7,33422,36541.4,39952,42264.0,46994.0
2644,66.3,66.6,61.2,63.2,70.1,48243,18.4,16.0,10.8,14.3,...,0.0,0.0,0.0,0.0,0.0,46534,53194.0,53088,56703.4,38659.0
2673,64.5,72.7,73.3,96.8,97.0,48301,4.7,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,80938,81875.0,83750,44076.0,86659.7

### Looks Reasonable

In [14]:
census_df.isna().sum()

pct_bb_2017              0
pct_bb_2018              0
pct_bb_2019              0
pct_bb_2020              0
pct_bb_2021              0
cfips                    0
pct_college_2017         0
pct_college_2018         0
pct_college_2019         0
pct_college_2020         0
pct_college_2021         0
pct_foreign_born_2017    0
pct_foreign_born_2018    0
pct_foreign_born_2019    0
pct_foreign_born_2020    0
pct_foreign_born_2021    0
pct_it_workers_2017      0
pct_it_workers_2018      0
pct_it_workers_2019      0
pct_it_workers_2020      0
pct_it_workers_2021      0
median_hh_inc_2017       0
median_hh_inc_2018       0
median_hh_inc_2019       0
median_hh_inc_2020       0
median_hh_inc_2021       0
dtype: int64

### Imputation Done