In [1]:
import pandas as pd
import numpy as np

import pickle
import json

In [2]:
dtypes = {'cfips': str}

# Load the data: AE_df.csv
AE_df = pd.read_csv('AE_df.csv', dtype=dtypes)

# Load the data: PCA_df.csv
PCA_df = pd.read_csv('PCA_df.csv', dtype=dtypes)

# Load the data: one_hot_df.csv
one_hot_df = pd.read_csv('one_hot_df.csv', dtype=dtypes)

In [3]:
AE_df.head()

,cfips,AE_dim_1,AE_dim_2,AE_dim_3,AE_dim_4,AE_dim_5,AE_dim_6,AE_dim_7,AE_dim_8,AE_dim_9,AE_dim_10
0,01001,-0.000740,0.000235,0.000044,0.000279,6.705523e-08,0.000106,-0.000065,0.000241,-0.000282,-0.000730
1,01003,0.000354,-0.000244,-0.000050,-0.000005,-1.353235e-04,-0.000333,0.000111,0.000104,0.000011,0.000164
2,01005,-0.000364,0.000122,0.000024,0.000149,-1.667081e-04,-0.000023,0.000028,0.000040,-0.000080,-0.000505
3,01007,0.000009,-0.000197,0.000925,0.000245,-3.897385e-04,-0.000478,0.000116,-0.000387,0.000032,0.000354
4,01009,-0.000177,-0.000038,0.000049,0.000193,-2.100589e-04,-0.000325,-0.000021,0.000004,-0.000118,-0.000382

In [4]:
PCA_df.head()

,cfips,PCA_dim_1,PCA_dim_2,PCA_dim_3,PCA_dim_4,PCA_dim_5,PCA_dim_6,PCA_dim_7,PCA_dim_8,PCA_dim_9,PCA_dim_10
0,01001,1.640334,0.260667,-0.150069,0.475759,0.130561,-0.035195,-0.332714,-0.021657,-0.231671,-0.127441
1,01003,1.604294,0.412023,-0.166257,0.240719,-0.208929,0.080796,0.038135,-0.153068,-0.361099,0.002606
2,01005,0.742398,0.115449,0.907438,0.317949,0.652057,-0.401865,0.096546,0.463242,0.120362,-0.330844
3,01007,0.812028,0.047316,1.085610,0.291032,0.694605,-0.339908,0.045470,0.669958,0.199610,-0.646288
4,01009,0.863453,0.101314,0.876775,0.450604,0.508579,-0.476478,0.006023,0.566877,-0.165812,-0.201319

In [5]:
one_hot_df.head()

,cfips,Connected_Economy,Government_Support,Large_Customer_Base,Low_Cost_of_Living,Natural_Resources,Supportive_Community,Limited_Financing,Limited_Tech_n_Infra,Low_Pop_Bad_Weather,Tough_Labor_Market,Unfavorable_Location,Various_Downsides
0,01001,1,0,0,1,0,0,0,0,0,0,1,0
1,01003,1,1,0,1,0,0,0,0,0,1,0,0
2,01005,0,1,1,1,0,0,0,0,0,1,1,0
3,01007,0,1,1,1,0,0,0,0,0,0,1,0
4,01009,0,1,1,1,0,0,1,0,0,0,1,0

In [6]:
AE_np = AE_df.iloc[:, 1:].to_numpy()
PCA_np = PCA_df.iloc[:, 1:].to_numpy()
one_hot_np = one_hot_df.iloc[:, 1:].to_numpy()

print(AE_np.shape)
print(PCA_np.shape)
print(one_hot_np.shape)

(3142, 10)
(3142, 10)
(3142, 12)

In [7]:
# concatenate the three arrays on the column axis
X = np.concatenate((AE_np, PCA_np, one_hot_np), axis=1)
X.shape

(3142, 32)

In [8]:
data_np = np.repeat(X[np.newaxis, :, :], 47, axis=0)
data_np.shape

(47, 3142, 32)

In [9]:
# swap the axis so that the shape is (3142, 5, 47)
data_np = np.swapaxes(data_np, 1, 2)
data_np.shape

(47, 32, 3142)

In [10]:
one_hot_df.columns

Index(['cfips', 'Connected_Economy', 'Government_Support',
       'Large_Customer_Base', 'Low_Cost_of_Living', 'Natural_Resources',
       'Supportive_Community', 'Limited_Financing', 'Limited_Tech_n_Infra',
       'Low_Pop_Bad_Weather', 'Tough_Labor_Market', 'Unfavorable_Location',
       'Various_Downsides'],
      dtype='object')

In [11]:
data_name = 'GPT_derived'
data_description = {'feature_0' : 'GPT_Autoencoder_dim0',
                    'feature_1' : 'GPT_Autoencoder_dim1',
                    'feature_2' : 'GPT_Autoencoder_dim2',
                    'feature_3' : 'GPT_Autoencoder_dim3',
                    'feature_4' : 'GPT_Autoencoder_dim4',
                    'feature_5' : 'GPT_Autoencoder_dim5',
                    'feature_6' : 'GPT_Autoencoder_dim6',
                    'feature_7' : 'GPT_Autoencoder_dim7',
                    'feature_8' : 'GPT_Autoencoder_dim8',
                    'feature_9' : 'GPT_Autoencoder_dim9',
                    'feature_10' : 'GPT_PCA_dim0',
                    'feature_11' : 'GPT_PCA_dim1',
                    'feature_12' : 'GPT_PCA_dim2',
                    'feature_13' : 'GPT_PCA_dim3',
                    'feature_14' : 'GPT_PCA_dim4',
                    'feature_15' : 'GPT_PCA_dim5',
                    'feature_16' : 'GPT_PCA_dim6',
                    'feature_17' : 'GPT_PCA_dim7',
                    'feature_18' : 'GPT_PCA_dim8',
                    'feature_19' : 'GPT_PCA_dim9',
                    'feature_20' : 'GPT_OH_Connected_Economy',
                    'feature_21' : 'GPT_OH_Government_Support',
                    'feature_22' : 'GPT_OH_Large_Customer_Base',
                    'feature_23' : 'GPT_OH_Low_Cost_of_Living',
                    'feature_24' : 'GPT_OH_Natural_Resources',
                    'feature_25' : 'GPT_OH_Supportive_Community',
                    'feature_26' : 'GPT_OH_Limited_Financing',
                    'feature_27' : 'GPT_OH_Limited_Tech_n_Infra',
                    'feature_28' : 'GPT_OH_Low_Pop_Bad_Weather',
                    'feature_29' : 'GPT_OH_Tough_Labor_Market',
                    'feature_30' : 'GPT_OH_Unfavorable_Location',
                    'feature_31' : 'GPT_OH_Various_Downsides',
                    }

# save data in pickle format
with open(f'BLOCKED_{data_name}_data.pkl', 'wb') as f:
    pickle.dump(data_np, f)

# save data in json format
with open(f'BLOCKED_{data_name}_data_description.json', 'w') as f:
    json.dump(data_description, f)